<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-04-17 14:15

$extensionPath = t3lib_extMgm::extPath('extracache');
return array(
    'tx_extracache_system_tools_fixtures_dummyobject' => $extensionPath . 'Tests/System/Tools/Fixtures/DummyObject.php',
);
?>